-- Adds every ISO 3166-1 alpha-2 country / territory.
-- Run AFTER schema.sql. Idempotent — `on conflict do nothing` means existing
-- rich-data rows (Japan, Italy, etc.) are preserved unchanged.

insert into public.countries (code, name, capital, continent, flag_emoji) values
('AF','Afghanistan','Kabul','Asia','🇦🇫'),
('AX','Åland Islands','Mariehamn','Europe','🇦🇽'),
('AL','Albania','Tirana','Europe','🇦🇱'),
('DZ','Algeria','Algiers','Africa','🇩🇿'),
('AS','American Samoa','Pago Pago','Oceania','🇦🇸'),
('AD','Andorra','Andorra la Vella','Europe','🇦🇩'),
('AO','Angola','Luanda','Africa','🇦🇴'),
('AI','Anguilla','The Valley','North America','🇦🇮'),
('AQ','Antarctica',null,'Antarctica','🇦🇶'),
('AG','Antigua and Barbuda','Saint John''s','North America','🇦🇬'),
('AR','Argentina','Buenos Aires','South America','🇦🇷'),
('AM','Armenia','Yerevan','Asia','🇦🇲'),
('AW','Aruba','Oranjestad','North America','🇦🇼'),
('AU','Australia','Canberra','Oceania','🇦🇺'),
('AT','Austria','Vienna','Europe','🇦🇹'),
('AZ','Azerbaijan','Baku','Asia','🇦🇿'),
('BS','Bahamas','Nassau','North America','🇧🇸'),
('BH','Bahrain','Manama','Asia','🇧🇭'),
('BD','Bangladesh','Dhaka','Asia','🇧🇩'),
('BB','Barbados','Bridgetown','North America','🇧🇧'),
('BY','Belarus','Minsk','Europe','🇧🇾'),
('BE','Belgium','Brussels','Europe','🇧🇪'),
('BZ','Belize','Belmopan','North America','🇧🇿'),
('BJ','Benin','Porto-Novo','Africa','🇧🇯'),
('BM','Bermuda','Hamilton','North America','🇧🇲'),
('BT','Bhutan','Thimphu','Asia','🇧🇹'),
('BO','Bolivia','Sucre','South America','🇧🇴'),
('BQ','Bonaire, Sint Eustatius and Saba','Kralendijk','North America','🇧🇶'),
('BA','Bosnia and Herzegovina','Sarajevo','Europe','🇧🇦'),
('BW','Botswana','Gaborone','Africa','🇧🇼'),
('BV','Bouvet Island',null,'Antarctica','🇧🇻'),
('BR','Brazil','Brasília','South America','🇧🇷'),
('IO','British Indian Ocean Territory','Diego Garcia','Asia','🇮🇴'),
('BN','Brunei','Bandar Seri Begawan','Asia','🇧🇳'),
('BG','Bulgaria','Sofia','Europe','🇧🇬'),
('BF','Burkina Faso','Ouagadougou','Africa','🇧🇫'),
('BI','Burundi','Gitega','Africa','🇧🇮'),
('CV','Cabo Verde','Praia','Africa','🇨🇻'),
('KH','Cambodia','Phnom Penh','Asia','🇰🇭'),
('CM','Cameroon','Yaoundé','Africa','🇨🇲'),
('CA','Canada','Ottawa','North America','🇨🇦'),
('KY','Cayman Islands','George Town','North America','🇰🇾'),
('CF','Central African Republic','Bangui','Africa','🇨🇫'),
('TD','Chad','N''Djamena','Africa','🇹🇩'),
('CL','Chile','Santiago','South America','🇨🇱'),
('CN','China','Beijing','Asia','🇨🇳'),
('CX','Christmas Island','Flying Fish Cove','Oceania','🇨🇽'),
('CC','Cocos (Keeling) Islands','West Island','Oceania','🇨🇨'),
('CO','Colombia','Bogotá','South America','🇨🇴'),
('KM','Comoros','Moroni','Africa','🇰🇲'),
('CG','Congo','Brazzaville','Africa','🇨🇬'),
('CD','Congo (DRC)','Kinshasa','Africa','🇨🇩'),
('CK','Cook Islands','Avarua','Oceania','🇨🇰'),
('CR','Costa Rica','San José','North America','🇨🇷'),
('CI','Côte d''Ivoire','Yamoussoukro','Africa','🇨🇮'),
('HR','Croatia','Zagreb','Europe','🇭🇷'),
('CU','Cuba','Havana','North America','🇨🇺'),
('CW','Curaçao','Willemstad','North America','🇨🇼'),
('CY','Cyprus','Nicosia','Europe','🇨🇾'),
('CZ','Czechia','Prague','Europe','🇨🇿'),
('DK','Denmark','Copenhagen','Europe','🇩🇰'),
('DJ','Djibouti','Djibouti','Africa','🇩🇯'),
('DM','Dominica','Roseau','North America','🇩🇲'),
('DO','Dominican Republic','Santo Domingo','North America','🇩🇴'),
('EC','Ecuador','Quito','South America','🇪🇨'),
('EG','Egypt','Cairo','Africa','🇪🇬'),
('SV','El Salvador','San Salvador','North America','🇸🇻'),
('GQ','Equatorial Guinea','Malabo','Africa','🇬🇶'),
('ER','Eritrea','Asmara','Africa','🇪🇷'),
('EE','Estonia','Tallinn','Europe','🇪🇪'),
('SZ','Eswatini','Mbabane','Africa','🇸🇿'),
('ET','Ethiopia','Addis Ababa','Africa','🇪🇹'),
('FK','Falkland Islands','Stanley','South America','🇫🇰'),
('FO','Faroe Islands','Tórshavn','Europe','🇫🇴'),
('FJ','Fiji','Suva','Oceania','🇫🇯'),
('FI','Finland','Helsinki','Europe','🇫🇮'),
('FR','France','Paris','Europe','🇫🇷'),
('GF','French Guiana','Cayenne','South America','🇬🇫'),
('PF','French Polynesia','Papeete','Oceania','🇵🇫'),
('TF','French Southern Territories','Saint-Pierre','Antarctica','🇹🇫'),
('GA','Gabon','Libreville','Africa','🇬🇦'),
('GM','Gambia','Banjul','Africa','🇬🇲'),
('GE','Georgia','Tbilisi','Asia','🇬🇪'),
('DE','Germany','Berlin','Europe','🇩🇪'),
('GH','Ghana','Accra','Africa','🇬🇭'),
('GI','Gibraltar','Gibraltar','Europe','🇬🇮'),
('GR','Greece','Athens','Europe','🇬🇷'),
('GL','Greenland','Nuuk','North America','🇬🇱'),
('GD','Grenada','Saint George''s','North America','🇬🇩'),
('GP','Guadeloupe','Basse-Terre','North America','🇬🇵'),
('GU','Guam','Hagåtña','Oceania','🇬🇺'),
('GT','Guatemala','Guatemala City','North America','🇬🇹'),
('GG','Guernsey','Saint Peter Port','Europe','🇬🇬'),
('GN','Guinea','Conakry','Africa','🇬🇳'),
('GW','Guinea-Bissau','Bissau','Africa','🇬🇼'),
('GY','Guyana','Georgetown','South America','🇬🇾'),
('HT','Haiti','Port-au-Prince','North America','🇭🇹'),
('HM','Heard Island and McDonald Islands',null,'Antarctica','🇭🇲'),
('VA','Holy See (Vatican City)','Vatican City','Europe','🇻🇦'),
('HN','Honduras','Tegucigalpa','North America','🇭🇳'),
('HK','Hong Kong','Hong Kong','Asia','🇭🇰'),
('HU','Hungary','Budapest','Europe','🇭🇺'),
('IS','Iceland','Reykjavík','Europe','🇮🇸'),
('IN','India','New Delhi','Asia','🇮🇳'),
('ID','Indonesia','Jakarta','Asia','🇮🇩'),
('IR','Iran','Tehran','Asia','🇮🇷'),
('IQ','Iraq','Baghdad','Asia','🇮🇶'),
('IE','Ireland','Dublin','Europe','🇮🇪'),
('IM','Isle of Man','Douglas','Europe','🇮🇲'),
('IL','Israel','Jerusalem','Asia','🇮🇱'),
('IT','Italy','Rome','Europe','🇮🇹'),
('JM','Jamaica','Kingston','North America','🇯🇲'),
('JP','Japan','Tokyo','Asia','🇯🇵'),
('JE','Jersey','Saint Helier','Europe','🇯🇪'),
('JO','Jordan','Amman','Asia','🇯🇴'),
('KZ','Kazakhstan','Astana','Asia','🇰🇿'),
('KE','Kenya','Nairobi','Africa','🇰🇪'),
('KI','Kiribati','Tarawa','Oceania','🇰🇮'),
('KP','North Korea','Pyongyang','Asia','🇰🇵'),
('KR','South Korea','Seoul','Asia','🇰🇷'),
('KW','Kuwait','Kuwait City','Asia','🇰🇼'),
('KG','Kyrgyzstan','Bishkek','Asia','🇰🇬'),
('LA','Laos','Vientiane','Asia','🇱🇦'),
('LV','Latvia','Riga','Europe','🇱🇻'),
('LB','Lebanon','Beirut','Asia','🇱🇧'),
('LS','Lesotho','Maseru','Africa','🇱🇸'),
('LR','Liberia','Monrovia','Africa','🇱🇷'),
('LY','Libya','Tripoli','Africa','🇱🇾'),
('LI','Liechtenstein','Vaduz','Europe','🇱🇮'),
('LT','Lithuania','Vilnius','Europe','🇱🇹'),
('LU','Luxembourg','Luxembourg','Europe','🇱🇺'),
('MO','Macao','Macao','Asia','🇲🇴'),
('MG','Madagascar','Antananarivo','Africa','🇲🇬'),
('MW','Malawi','Lilongwe','Africa','🇲🇼'),
('MY','Malaysia','Kuala Lumpur','Asia','🇲🇾'),
('MV','Maldives','Malé','Asia','🇲🇻'),
('ML','Mali','Bamako','Africa','🇲🇱'),
('MT','Malta','Valletta','Europe','🇲🇹'),
('MH','Marshall Islands','Majuro','Oceania','🇲🇭'),
('MQ','Martinique','Fort-de-France','North America','🇲🇶'),
('MR','Mauritania','Nouakchott','Africa','🇲🇷'),
('MU','Mauritius','Port Louis','Africa','🇲🇺'),
('YT','Mayotte','Mamoudzou','Africa','🇾🇹'),
('MX','Mexico','Mexico City','North America','🇲🇽'),
('FM','Micronesia','Palikir','Oceania','🇫🇲'),
('MD','Moldova','Chișinău','Europe','🇲🇩'),
('MC','Monaco','Monaco','Europe','🇲🇨'),
('MN','Mongolia','Ulaanbaatar','Asia','🇲🇳'),
('ME','Montenegro','Podgorica','Europe','🇲🇪'),
('MS','Montserrat','Plymouth','North America','🇲🇸'),
('MA','Morocco','Rabat','Africa','🇲🇦'),
('MZ','Mozambique','Maputo','Africa','🇲🇿'),
('MM','Myanmar','Naypyidaw','Asia','🇲🇲'),
('NA','Namibia','Windhoek','Africa','🇳🇦'),
('NR','Nauru','Yaren','Oceania','🇳🇷'),
('NP','Nepal','Kathmandu','Asia','🇳🇵'),
('NL','Netherlands','Amsterdam','Europe','🇳🇱'),
('NC','New Caledonia','Nouméa','Oceania','🇳🇨'),
('NZ','New Zealand','Wellington','Oceania','🇳🇿'),
('NI','Nicaragua','Managua','North America','🇳🇮'),
('NE','Niger','Niamey','Africa','🇳🇪'),
('NG','Nigeria','Abuja','Africa','🇳🇬'),
('NU','Niue','Alofi','Oceania','🇳🇺'),
('NF','Norfolk Island','Kingston','Oceania','🇳🇫'),
('MK','North Macedonia','Skopje','Europe','🇲🇰'),
('MP','Northern Mariana Islands','Saipan','Oceania','🇲🇵'),
('NO','Norway','Oslo','Europe','🇳🇴'),
('OM','Oman','Muscat','Asia','🇴🇲'),
('PK','Pakistan','Islamabad','Asia','🇵🇰'),
('PW','Palau','Ngerulmud','Oceania','🇵🇼'),
('PS','Palestine','Ramallah','Asia','🇵🇸'),
('PA','Panama','Panama City','North America','🇵🇦'),
('PG','Papua New Guinea','Port Moresby','Oceania','🇵🇬'),
('PY','Paraguay','Asunción','South America','🇵🇾'),
('PE','Peru','Lima','South America','🇵🇪'),
('PH','Philippines','Manila','Asia','🇵🇭'),
('PN','Pitcairn','Adamstown','Oceania','🇵🇳'),
('PL','Poland','Warsaw','Europe','🇵🇱'),
('PT','Portugal','Lisbon','Europe','🇵🇹'),
('PR','Puerto Rico','San Juan','North America','🇵🇷'),
('QA','Qatar','Doha','Asia','🇶🇦'),
('RE','Réunion','Saint-Denis','Africa','🇷🇪'),
('RO','Romania','Bucharest','Europe','🇷🇴'),
('RU','Russia','Moscow','Europe','🇷🇺'),
('RW','Rwanda','Kigali','Africa','🇷🇼'),
('BL','Saint Barthélemy','Gustavia','North America','🇧🇱'),
('SH','Saint Helena','Jamestown','Africa','🇸🇭'),
('KN','Saint Kitts and Nevis','Basseterre','North America','🇰🇳'),
('LC','Saint Lucia','Castries','North America','🇱🇨'),
('MF','Saint Martin','Marigot','North America','🇲🇫'),
('PM','Saint Pierre and Miquelon','Saint-Pierre','North America','🇵🇲'),
('VC','Saint Vincent and the Grenadines','Kingstown','North America','🇻🇨'),
('WS','Samoa','Apia','Oceania','🇼🇸'),
('SM','San Marino','San Marino','Europe','🇸🇲'),
('ST','São Tomé and Príncipe','São Tomé','Africa','🇸🇹'),
('SA','Saudi Arabia','Riyadh','Asia','🇸🇦'),
('SN','Senegal','Dakar','Africa','🇸🇳'),
('RS','Serbia','Belgrade','Europe','🇷🇸'),
('SC','Seychelles','Victoria','Africa','🇸🇨'),
('SL','Sierra Leone','Freetown','Africa','🇸🇱'),
('SG','Singapore','Singapore','Asia','🇸🇬'),
('SX','Sint Maarten','Philipsburg','North America','🇸🇽'),
('SK','Slovakia','Bratislava','Europe','🇸🇰'),
('SI','Slovenia','Ljubljana','Europe','🇸🇮'),
('SB','Solomon Islands','Honiara','Oceania','🇸🇧'),
('SO','Somalia','Mogadishu','Africa','🇸🇴'),
('ZA','South Africa','Pretoria','Africa','🇿🇦'),
('GS','South Georgia and the South Sandwich Islands','King Edward Point','Antarctica','🇬🇸'),
('SS','South Sudan','Juba','Africa','🇸🇸'),
('ES','Spain','Madrid','Europe','🇪🇸'),
('LK','Sri Lanka','Sri Jayawardenepura Kotte','Asia','🇱🇰'),
('SD','Sudan','Khartoum','Africa','🇸🇩'),
('SR','Suriname','Paramaribo','South America','🇸🇷'),
('SJ','Svalbard and Jan Mayen','Longyearbyen','Europe','🇸🇯'),
('SE','Sweden','Stockholm','Europe','🇸🇪'),
('CH','Switzerland','Bern','Europe','🇨🇭'),
('SY','Syria','Damascus','Asia','🇸🇾'),
('TW','Taiwan','Taipei','Asia','🇹🇼'),
('TJ','Tajikistan','Dushanbe','Asia','🇹🇯'),
('TZ','Tanzania','Dodoma','Africa','🇹🇿'),
('TH','Thailand','Bangkok','Asia','🇹🇭'),
('TL','Timor-Leste','Dili','Asia','🇹🇱'),
('TG','Togo','Lomé','Africa','🇹🇬'),
('TK','Tokelau','Nukunonu','Oceania','🇹🇰'),
('TO','Tonga','Nukuʻalofa','Oceania','🇹🇴'),
('TT','Trinidad and Tobago','Port of Spain','North America','🇹🇹'),
('TN','Tunisia','Tunis','Africa','🇹🇳'),
('TR','Türkiye','Ankara','Asia','🇹🇷'),
('TM','Turkmenistan','Ashgabat','Asia','🇹🇲'),
('TC','Turks and Caicos Islands','Cockburn Town','North America','🇹🇨'),
('TV','Tuvalu','Funafuti','Oceania','🇹🇻'),
('UG','Uganda','Kampala','Africa','🇺🇬'),
('UA','Ukraine','Kyiv','Europe','🇺🇦'),
('AE','United Arab Emirates','Abu Dhabi','Asia','🇦🇪'),
('GB','United Kingdom','London','Europe','🇬🇧'),
('US','United States','Washington, D.C.','North America','🇺🇸'),
('UM','U.S. Minor Outlying Islands',null,'Oceania','🇺🇲'),
('UY','Uruguay','Montevideo','South America','🇺🇾'),
('UZ','Uzbekistan','Tashkent','Asia','🇺🇿'),
('VU','Vanuatu','Port Vila','Oceania','🇻🇺'),
('VE','Venezuela','Caracas','South America','🇻🇪'),
('VN','Vietnam','Hanoi','Asia','🇻🇳'),
('VG','British Virgin Islands','Road Town','North America','🇻🇬'),
('VI','U.S. Virgin Islands','Charlotte Amalie','North America','🇻🇮'),
('WF','Wallis and Futuna','Mata-Utu','Oceania','🇼🇫'),
('EH','Western Sahara','El Aaiún','Africa','🇪🇭'),
('YE','Yemen','Sanaa','Asia','🇾🇪'),
('ZM','Zambia','Lusaka','Africa','🇿🇲'),
('ZW','Zimbabwe','Harare','Africa','🇿🇼')
on conflict (code) do nothing;
